Rise-Vision/displays-app

- bower.json
- circle.yml
Removed .htaccess file creation
@tejohnso adding this as per our discussion in https://trello.com/c/rd5sYlfy/228-apps-ftp-deployment-detect-folder-creation-failure-or-create-parent-folder-automatically.
Build is fixed in the other PR. 
@tejohnso and/or @EnlightenedCode please review this and #1? Thanks.
> [fix] Create full folder path

- README.md
- gulpfile.js
- index.html
- js/app.js
- js/controllers/ctr-app.js
- js/directives/dtv-displays-list.js
- js/filters/ftr-status.js
- js/services/svc-display.js
- partials/displays-list.html
- partials/home.html
- partials/on-boarding.html
- test/e2e/app.scenarios.js
- test/unit/filters/ftr-status.tests.js
- test/unit/karma.conf.js
App.js initializes all modules
Added app controller w/ basic route
Added test infrastructure
Displays directive w/ controller and service
Status filter for Display status w/ tests
> [feature] Displays list with infinite scroll

- index.html
- js/directives/dtv-displays-filter.js
- js/directives/dtv-displays-list.js
- js/filters/ftr-status.js
- js/services/svc-display.js
- partials/displays-filter.html
- partials/displays-list.html
- partials/home.html
- partials/lookup.html
- test/unit/services/svc-display.tests.js
Refactored display service to be more angularized
Added tests for service
Added displays filter with tagging UI features
Only text box search works at this point
Also includes jsbeautify results.
> [feature] Added a simple search filter

- index.html
- js/app.js
- js/controllers/ctr-delete-instance.js
- js/controllers/ctr-display-details.js
- js/directives/dtv-display-details.js
- js/directives/dtv-time-picker.js
- js/filters/ftr-resolution.js
- js/services/svc-display.js
- js/services/svc-time-parser.js
- partials/delete-modal.html
- partials/display-details.html
- partials/display.html
- partials/displays-list.html
- partials/displays.html
- partials/home.html
- partials/on-boarding.html
- partials/time-picker.html
- test/unit/controllers/ctr-app.tests.js
- test/unit/services/svc-time-parser.tests.js
Updated routing
Fixed button styling
Time picker directive, resolution filter and delete modal
@EnlightenedCode Manage Display is not quite finished but adding/loading a display works. Please review. Thanks.
> [feature] Manage display page

- index.html
- js/controllers/ctr-confirm-instance.js
- js/controllers/ctr-display-controls.js
- js/controllers/ctr-display-details.js
- partials/confirm-modal.html
- partials/display-fields.html
- test/unit/controllers/ctr-display-controls.tests.js
Created more general confirm dialogue
Added confirmation for restart/reboot buttons
Updated tests
PR needs to be merged after #5.
@EnlightenedCode please review. Thanks.
> [feature] Added confirmation for restart/reboot

- bower.json
- index.html
- js/controllers/ctr-display-controls.js
- js/controllers/ctr-display-details.js
- partials/confirm-modal.html
- partials/display-add.html
- partials/display-details.html
- partials/display-fields.html
- partials/displays-filter.html
- partials/displays-list.html
- partials/home.html
- partials/on-boarding.html
PR needs to be merged after #5 and #6.
@EnlightenedCode please review. Thanks.
> [feature] Updated app strings to use i18n constants

- bower.json
@EnlightenedCode missed this in the last PR. Please review. Thanks.
> [fix] Removing branch tag from bower

- bower.json
@EnlightenedCode master build is currently broken because of this. Please review. Thanks.
> [fix] Removing common style branch tag

- bower.json
- index.html
- js/controllers/ctr-app.js
- js/controllers/ctr-display-add.js
- js/controllers/ctr-display-controls.js
- js/directives/dtv-last-modified.js
- js/filters/ftr-username.js
- partials/display-details.html
- partials/display-fields.html
- partials/displays-list.html
- partials/last-modified.html
- test/unit/controllers/ctr-display-add.tests.js
- test/unit/filters/ftr-username.tests.js
Added last modified field to Display Manage
Updated CH navigation links
Setting monitoringEnabled = true by default on Display Add
Style updates for Display list and fields
Using CH and style guide branch versions
> [feature] Last modified and other UX improvements

- partials/display-add.html
- partials/display-fields.html
Updated Display Fields UX by reordering fields
Added orientation field
On Add Display, just showing app Title (no more Add button)
@olegrise please review this and the corresponding common-i18n PR: https://github.com/Rise-Vision/common-i18n/pull/62. 
Thanks!
> [feature] UX Improvements

- gulpfile.js
Currently causing injector issues with `$routeProvider`
@olegrise please review. Thanks!
> [fix] Disabled mangle for the build

- gulpfile.js
- js/app.js
@olegrise check it out! I just tried this and it works. This seems to fix the issue with mangle and `$routeProvider`! I could never imagine writing the dependency injections like this would work...
> [fix] Fixing injector for mangle

- js/app.js
- js/config/dev.js
- js/config/prod.js
- js/config/test.js
@olegrise please review. Thanks!
> [feature] Overwriting Core URL for dev/test

- bower.json
@olegrise please review. Thanks!
> [chore] Updating ch version

- bower.json
- js/filters/ftr-status.js
- js/services/svc-display.js
- partials/display-fields.html
- partials/displays-list.html
- test/unit/filters/ftr-status.tests.js
Remove company id from query
Use lastConnectionDate rather than lastActivityDate
> [feature] Configured display fields

- bower.json
- js/controllers/ctr-display-add.js
- js/filters/ftr-status.js
- js/services/svc-display.js
- partials/display-fields.html
- test/unit/filters/ftr-status.tests.js
- test/unit/services/svc-display.tests.js
Added orientation to API fields
Fixed issue with select element ng-model
Updated CH and common-style versions
> [fix] playerStatus renamed to playerErrorCode

- bower.json
@olegrise please review. Thanks!
> [chore] Update CH and CS versions

- .gitignore
- circle.yml
to CE. It also checks for tag on the commit message
when deploying to stage. [stage-0]
@alex-deaconu could you please review? Thanks.
> Changed cci build to deploy displays app

- index.html
@alex-deaconu could you please review? Cheers.
> Updated metadata tags. [stage-0]

- bower.json
@alex-deaconu please review. Thanks.
> Updated CH to 1.1.2. [stage-0]

- index.html
@alex-deaconu please review. cheers.
> Added sitename and webmaster metadata tags

- partials/display-fields.html
Updated i18n constants as per https://github.com/Rise-Vision/common-i18n/pull/79.
@rodrigopavezi please review. Thanks
> [feature] Updated player warning & orientation field

- bower.json
- index.html
- js/app.js
- js/controllers/ctr-display-add.js
- js/controllers/ctr-display-details.js
- js/controllers/ctr-displays-list.js
- js/directives/dtv-display-fields.js
- js/services/svc-access.js
- js/services/svc-time-parser.js
- partials/display-add.html
- partials/display-details.html
- partials/display-fields.html
- partials/displays-list.html
- test/unit/controllers/ctr-display-add.tests.js
- test/unit/controllers/ctr-display-details.tests.js
- test/unit/controllers/ctr-displays-list.tests.js
- test/unit/services/svc-access.tests.js
Using .go and ui-sref for navigation
Integrated risevision.company.selectedCompanyChanged event`
Updated tests
Removed extra bower dependencies imported by CH
> [feature] Integrated ui.router

- bower.json
- partials/display-add.html
- partials/display-details.html
- partials/display-fields.html
- partials/displays-list.html
@alex-deaconu I'm pushing the list and scroll bar visibility fix. We also need to use the same solution we had for selectors. You will see I've added a script a the bottom for showing how it should work.
```
<script type="text/javascript">
$(window).resize(function() {
$('.auto-height').height($(window).height() -  $('.app-header').height() -  $('.navbar').height() - $('.app-footer').height() - 140);
});
$(window).trigger('resize');
</script>
```
> [feature] ux updates

- js/app.js
For some reason I missed this code in the ui-router PR. Added back in.
@rodrigopavezi please review. Thanks!
> [fix] Adding missing company change event [stage-1]

- js/app.js
Setting root '/' path as signed out path
When on root path, check authentication to see if user can proceed
Reload state when company changes from root path
> Fix signed out user & user registration [stage-0]

- .jshintrc
- js/filters/ftr-resolution.js
- js/services/svc-display.js
- test/unit/controllers/ctr-comfirm-instance.tests.js
- test/unit/controllers/ctr-display-add.tests.js
- test/unit/controllers/ctr-display-controls.tests.js
- test/unit/controllers/ctr-displays-list.tests.js
- test/unit/controllers/ctr-monitoring.tests.js
- test/unit/filters/ftr-resolution.tests.js
- test/unit/filters/ftr-status.tests.js
- test/unit/karma.conf.js
- test/unit/services/svc-display.tests.js
@alex-deaconu I reverted back the changes to the package.json for e2e tests. I think it is ready for merging. Awaiting your review. cheers
> Increased test coverage [stage-1]

- js/directives/dtv-time-picker.js
- partials/display-fields.html
- partials/time-picker.html
Unfortunately the ui-bootstrap component doesn't support ngDisabled
Fixing scope variable
@rodrigopavezi please review. Thanks.
> [feature] Adding disable property to time-picker [stage-0]

- js/controllers/ctr-app.js
@rodrigopavezi removing link as per this card: https://trello.com/c/V4kqZt91/321-remove-help-link-from-ch-menu.
Please review. Thanks!
> [chore] Removed help link [stage-0]

- bower.json
- index.html
- js/app.js
- js/controllers/ctr-display-add.js
- js/controllers/ctr-display-controls.js
- js/controllers/ctr-display-details.js
- js/services/svc-display-tracker.js
- partials/display-fields.html
- test/unit/controllers/ctr-display-add.tests.js
- test/unit/controllers/ctr-display-controls.tests.js
- test/unit/controllers/ctr-display-details.tests.js
- test/unit/services/svc-display-tracker.tests.js
Updating ch version
Added tracker service & tracking functions
> Setting up segment tracking [stage-2]

- gulpfile.js
- index.html
Removed libraries are available through dependencies.js from CH
@rodrigopavezi please review. Thanks!
> [chore] Cleaned up index.html scripts

- js/controllers/ctr-displays-list.js
- js/directives/dtv-time-picker.js
- test/unit/controllers/ctr-displays-list.tests.js
@rodrigopavezi please review. Thanks.
> [fix] Send translated string to search placeholder [stage-0]

- js/app.js
- js/directives/dtv-display-fields.js
- package.json
- partials/landing-page.html
- test/e2e/homepage.scenarios.js
- test/e2e/pages/commonheaderpage.js
- test/e2e/pages/googleAuthPage.js
- test/e2e/pages/homepage.js
[stage-0]
@alex-deaconu please review. cheers
> Implemented displays landing page

- partials/landing-page.html
- test/e2e/homepage.scenarios.js
@alex-deaconu I have fixed missing texts and added e2e for checking them. Please review. cheers
> Fixed missing texts

- circle.yml
- package.json
Adding chai back to package.json
> [chore] Removing chromedriver & selenium preload

- partials/display-add.html
- partials/display-details.html
- test/e2e/common/helper.js
- test/e2e/displayadd.scenarios.js
- test/e2e/pages/displayAddPage.js
@alex-deaconu please review. I will move the common e2e scripts to a node module when I get a chance. cheers
> Fixed add displays test to delete the added display.

- bower.json
@rodrigopavezi please review. Thanks!
> Updating CH and common-style versions

- bower.json
- js/app.js
> Updating CH to v1.4.2

- partials/display-fields.html
> Updated player download url

- partials/landing-page.html
- test/e2e/homepage.scenarios.js
@rodrigopavezi I changed the landing page text and reused common messages for signup and signin.
> Changing landing page messages

- circle.yml
@rodrigopavezi  Tags ([stage-0],[stage-1],...) are still working.
> Update CCI script to default deploy to stage-0.

- index.html
- test/e2e/homepage.scenarios.js
- test/e2e/pages/homepage.js
@rodrigopavezi please review. thanks!
> Update Displays meta data

- bower.json
- package.json
Fixed use-min version (resolves build problem)
> Update CH version

- partials/display-fields.html
@tejohnso @alex-deaconu please review
> Add Player's local IP address

- bower.json
@ghislaineguerin Please review. Cheers.
@rodrigopavezi @alex-deaconu FYI
> update dependencies [stage-1]

- bower.json
- circle.yml
- gulpfile.js
- js/config/stage.js
- test/unit/controllers/ctr-display-add.tests.js
- test/unit/controllers/ctr-display-controls.tests.js
- test/unit/controllers/ctr-display-details.tests.js
- test/unit/controllers/ctr-displays-list.tests.js
@ezequielc please review. cheers
> Upgraded CH and CS

- README.md
- gulpfile.js
- package.json
@rodrigopavezi Please review. Thanks
> Code coverage and coveralls

- package.json
@ezequielc please review. cheers
> Added version to rv-common-e2e

- bower.json
- js/config/test.js
@rodrigopavezi 
Please review, another Common Style update here
@ezequielc 
Note the line break in `test.js` here as well.
Thx!
> Update to Common Style 1.3.21 [stage-1]

- bower.json
- gulpfile.js
- index.html
- package.json
- test/e2e/cases/homepage.js
- test/e2e/pages/homepage.js
@ezequielc please review. cheers
> Upgraded CH to the auth 2 version

- bower.json
- package.json
@ezequielc please review. cheers
> Rolled back auth2

- bower.json
- partials/display-add.html
- partials/display-details.html
- partials/display-fields.html
- partials/displays-list.html
Use require-role directive to remove actions if not allowed
> Check Display Administrator role

- bower.json
- gulpfile.js
- index.html
- js/app.js
- package.json
> Prepopulate partials into templateCache

- js/app.js
- js/controllers/ctr-displays-list.js
- partials/displays-list.html
Show warning only when a search filter is active
Highlight sub-company displays
[stage-2]
> Change selectedCompanyId to display's company

- js/app.js
- js/controllers/ctr-display-add.js
- js/controllers/ctr-display-details.js
- js/controllers/ctr-displays-list.js
- partials/displays-list.html
- test/unit/controllers/ctr-display-add.tests.js
- test/unit/controllers/ctr-display-details.tests.js
- test/unit/controllers/ctr-displays-list.tests.js
@alex-deaconu Please review. Cheers
> Tracking events for adding and saving displays
